name: Branch Name Check
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          PATTERN="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)/AID-[0-9]+/[a-z0-9-]+$"
          if [[ ! "$BRANCH_NAME" =~ $PATTERN ]]; then
            echo "Error: Branch name '$BRANCH_NAME' does not follow the convention: type/AID-<digits>/description"
            echo "Expected format: feat/AID-123/short-description"
            exit 1
          fi
          echo "Branch name '$BRANCH_NAME' is valid and follows the convention."